const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
let currentUser=null,profile=null,selectedUser=null,channel=null,presenceChannel=null,authMode="login",mediaRecorder=null,recordChunks=[],recordTimer=null,recordStart=0,onlineUsers=new Set();
const $=id=>document.getElementById(id);const initials=(n="User")=>n.trim().slice(0,1).toUpperCase();
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>$("toast").classList.remove("show"),3200)}
function escapeHtml(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML}function fmtSize(n){if(!n)return"";const u=["B","KB","MB","GB"];let i=0,x=n;while(x>=1024&&i<3){x/=1024;i++}return`${x.toFixed(i?1:0)} ${u[i]}`}
function avatarHtml(p){return p?.avatar_url?`<img src="${encodeURI(p.avatar_url)}" alt="">`:escapeHtml(initials(p?.display_name))}
function isOnline(id){return onlineUsers.has(id)}
function relativeLastSeen(date){if(!date)return"Offline";const s=Math.max(0,Math.floor((Date.now()-new Date(date))/1000));if(s<60)return"last active just now";if(s<3600)return`last active ${Math.floor(s/60)} min ago`;if(s<86400)return`last active ${Math.floor(s/3600)} hr ago`;return`last active ${Math.floor(s/86400)} day ago`}
function updateChatStatus(){if(!selectedUser)return;const on=isOnline(selectedUser.id);$("chatStatus").textContent=on?"Active now":relativeLastSeen(selectedUser.last_seen);$("chatOnlineDot").classList.toggle("hidden",!on)}
function renderMyProfile(){if(!profile)return;$("myName").textContent=profile.display_name;$("myEmail").textContent=currentUser.email;$("myAvatar").innerHTML=avatarHtml(profile);$("settingsAvatar").innerHTML=avatarHtml(profile);$("settingsName").value=profile.display_name;$("myOnlineDot").classList.remove("hidden")}
function applyTheme(theme){document.body.dataset.theme=theme;document.documentElement.classList.remove("theme-purple","theme-blue","theme-green");if(["purple","blue","green"].includes(theme))document.documentElement.classList.add("theme-"+theme);localStorage.setItem("chats-theme",theme);document.querySelectorAll(".theme-choice").forEach(b=>b.classList.toggle("active",b.dataset.theme===theme))}
applyTheme(localStorage.getItem("chats-theme")||"dark");

document.querySelectorAll("[data-auth]").forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("displayName").classList.toggle("hidden",authMode!=="signup");$("authButton").textContent=authMode==="signup"?"Create account":"Login"});
$("authForm").onsubmit=async e=>{e.preventDefault();const email=$("email").value.trim(),password=$("password").value;if(authMode==="signup"){const name=$("displayName").value.trim()||email.split("@")[0];const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)return toast(error.message);if(data.session)await startApp(data.user);else toast("Account created. Check your email, then login.")}else{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);await startApp(data.user)}};
$("logoutBtn").onclick=async()=>{await setLastSeen();await sb.auth.signOut();location.reload()};$("backBtn").onclick=()=>{selectedUser=null;$("chatPanel").classList.add("hidden");$("emptyChat").classList.remove("hidden")};$("settingsBtn").onclick=()=>{$("settingsModal").classList.remove("hidden");renderMyProfile()};$("myProfileBtn").onclick=()=>{$("settingsModal").classList.remove("hidden");renderMyProfile()};$("closeSettings").onclick=()=>$("settingsModal").classList.add("hidden");$("settingsModal").onclick=e=>{if(e.target===$("settingsModal"))$("settingsModal").classList.add("hidden")};
document.querySelectorAll(".theme-choice").forEach(b=>b.onclick=()=>applyTheme(b.dataset.theme));
async function startApp(user){currentUser=user;$("authView").classList.add("hidden");$("appView").classList.remove("hidden");await ensureProfile();await loadUsers();await setupPresence();requestNotifications();registerSW();setInterval(updateChatStatus,30000)}
async function ensureProfile(){let {data,error}=await sb.from("profiles").select("*").eq("id",currentUser.id).maybeSingle();if(error)return toast(error.message);if(!data){const displayName=currentUser.user_metadata?.display_name||currentUser.email.split("@")[0];const r=await sb.from("profiles").insert({id:currentUser.id,display_name:displayName,last_seen:new Date().toISOString()}).select().single();if(r.error)return toast(r.error.message);data=r.data}profile=data;renderMyProfile();await setLastSeen()}
async function setLastSeen(){if(!currentUser)return;const now=new Date().toISOString();profile={...(profile||{}),last_seen:now};await sb.from("profiles").update({last_seen:now}).eq("id",currentUser.id)}
async function setupPresence(){presenceChannel=sb.channel("online-users",{config:{presence:{key:currentUser.id}}});presenceChannel.on("presence",{event:"sync"},()=>{const state=presenceChannel.presenceState();onlineUsers=new Set(Object.keys(state));renderUsers(window._users||[]);updateChatStatus()}).on("presence",{event:"join"},({key})=>{onlineUsers.add(key);renderUsers(window._users||[]);updateChatStatus()}).on("presence",{event:"leave"},({key})=>{onlineUsers.delete(key);renderUsers(window._users||[]);updateChatStatus()}).subscribe(async status=>{if(status==="SUBSCRIBED"){await presenceChannel.track({online_at:new Date().toISOString()});}})}
async function loadUsers(){const {data,error}=await sb.from("profiles").select("id,display_name,avatar_url,last_seen,created_at").neq("id",currentUser.id).order("display_name");if(error)return toast(error.message);window._users=data||[];renderUsers(window._users);$("userSearch").oninput=e=>renderUsers(window._users.filter(u=>u.display_name.toLowerCase().includes(e.target.value.toLowerCase())))}
function renderUsers(users){const list=$("userList");list.innerHTML="";if(!users.length){list.innerHTML='<div class="no-users">No other users yet.</div>';return}users.forEach(u=>{const el=document.createElement("div");el.className="user-item"+(selectedUser?.id===u.id?" active":"");el.innerHTML=`<div class="avatar-wrap"><div class="avatar">${avatarHtml(u)}</div>${isOnline(u.id)?'<span class="online-dot"></span>':''}</div><div class="user-info"><strong>${escapeHtml(u.display_name)}</strong><span>${isOnline(u.id)?"Active now":relativeLastSeen(u.last_seen)}</span></div>`;el.onclick=()=>openChat(u);list.appendChild(el)})}
async function openChat(user){selectedUser=user;$("emptyChat").classList.add("hidden");$("chatPanel").classList.remove("hidden");$("chatName").textContent=user.display_name;$("chatAvatar").innerHTML=avatarHtml(user);updateChatStatus();if(channel)await sb.removeChannel(channel);await loadMessages();channel=sb.channel("messages:"+[currentUser.id,user.id].sort().join(":")).on("postgres_changes",{event:"*",schema:"public",table:"messages"},payload=>{const m=payload.new;if((m.sender_id===currentUser.id&&m.receiver_id===user.id)||(m.sender_id===user.id&&m.receiver_id===currentUser.id)){if(payload.eventType==="INSERT"){appendMessage(m);if(m.sender_id!==currentUser.id){markRead();notifyIncoming(m)}}else if(payload.eventType==="UPDATE"){updateMessage(m)}}}).subscribe();await markRead()}
async function loadMessages(){const ids=[currentUser.id,selectedUser.id];const {data,error}=await sb.from("messages").select("*").or(`and(sender_id.eq.${ids[0]},receiver_id.eq.${ids[1]}),and(sender_id.eq.${ids[1]},receiver_id.eq.${ids[0]})`).order("created_at",{ascending:true});if(error)return toast(error.message);$("messages").innerHTML="";(data||[]).forEach(appendMessage);scrollMessages()}
function messageBody(m){if(m.message_type==="file"&&m.file_url){if((m.file_type||"").startsWith("image/"))return`<a class="attachment" href="${encodeURI(m.file_url)}" target="_blank" rel="noopener"><img src="${encodeURI(m.file_url)}" alt="Image"></a>`;return`<a class="attachment" href="${encodeURI(m.file_url)}" target="_blank" rel="noopener"><div class="file-card"><div class="file-name">📎 ${escapeHtml(m.file_name||"File")}</div><div class="file-meta">${escapeHtml(fmtSize(m.file_size))}</div></div></a>`}if(m.message_type==="voice"&&m.file_url)return`<audio controls preload="metadata" src="${encodeURI(m.file_url)}"></audio>`;return escapeHtml(m.content)}
function appendMessage(m){if(document.querySelector(`[data-msg="${m.id}"]`))return;const el=document.createElement("div");el.className="message "+(m.sender_id===currentUser.id?"mine":"theirs");el.dataset.msg=m.id;el.innerHTML=`${messageBody(m)}<div class="msg-meta"><span>${new Date(m.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span>${m.sender_id===currentUser.id&&m.read_at?'<span class="seen">Seen</span>':''}</div>`;$("messages").appendChild(el);scrollMessages()}
function updateMessage(m){const old=document.querySelector(`[data-msg="${m.id}"]`);if(old)old.querySelector(".msg-meta").innerHTML=`<span>${new Date(m.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span>${m.sender_id===currentUser.id&&m.read_at?'<span class="seen">Seen</span>':''}`}
$("messageForm").onsubmit=async e=>{e.preventDefault();const content=$("messageInput").value.trim();if(!content||!selectedUser)return;$("messageInput").value="";const {error}=await sb.from("messages").insert({sender_id:currentUser.id,receiver_id:selectedUser.id,content,message_type:"text"});if(error){toast(error.message);$("messageInput").value=content}};
$("attachBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=async e=>{const f=e.target.files?.[0];if(!f||!selectedUser)return;await sendFile(f,"file");e.target.value=""};
async function sendFile(file,type){if(file.size>25*1024*1024)return toast("File is too large. Maximum 25 MB.");toast("Uploading…");const safe=`${currentUser.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:up}=await sb.storage.from("chat-files").upload(safe,file,{contentType:file.type||"application/octet-stream",upsert:false});if(up)return toast("Upload failed: "+up.message);const {data}=sb.storage.from("chat-files").getPublicUrl(safe);const {error}=await sb.from("messages").insert({sender_id:currentUser.id,receiver_id:selectedUser.id,content:file.name,message_type:type,file_url:data.publicUrl,file_name:file.name,file_type:file.type,file_size:file.size});if(error)toast(error.message);else toast("Sent")}
$("voiceBtn").onclick=startRecording;$("cancelRecording").onclick=cancelRecording;$("stopRecording").onclick=stopRecording;
async function startRecording(){if(!selectedUser)return;if(!navigator.mediaDevices?.getUserMedia)return toast("Voice recording is not supported here.");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);recordChunks=[];mediaRecorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};mediaRecorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());if(!recordChunks.length)return;const blob=new Blob(recordChunks,{type:mediaRecorder.mimeType||"audio/webm"});const file=new File([blob],`voice-${Date.now()}.webm`,{type:blob.type});await sendFile(file,"voice")};mediaRecorder.start();recordStart=Date.now();$("recordingBar").classList.remove("hidden");updateRecordTimer();recordTimer=setInterval(updateRecordTimer,500)}catch(e){toast("Microphone permission was denied.")}}
function updateRecordTimer(){const s=Math.floor((Date.now()-recordStart)/1000);$("recordingTime").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}function stopRecording(){if(!mediaRecorder)return;clearInterval(recordTimer);$("recordingBar").classList.add("hidden");mediaRecorder.stop();mediaRecorder=null}function cancelRecording(){if(!mediaRecorder)return;clearInterval(recordTimer);mediaRecorder.onstop=null;mediaRecorder.stream?.getTracks().forEach(t=>t.stop());mediaRecorder.stop();mediaRecorder=null;$("recordingBar").classList.add("hidden")}
async function markRead(){if(!selectedUser)return;const {error}=await sb.from("messages").update({read_at:new Date().toISOString()}).eq("sender_id",selectedUser.id).eq("receiver_id",currentUser.id).is("read_at",null);if(error)return;const msgs=await sb.from("messages").select("id,read_at").eq("sender_id",currentUser.id).eq("receiver_id",selectedUser.id);(msgs.data||[]).forEach(updateMessage)}function scrollMessages(){requestAnimationFrame(()=>$('messages').scrollTop=$('messages').scrollHeight)}
function requestNotifications(){if("Notification"in window&&Notification.permission==="default")Notification.requestPermission().catch(()=>{})}function notifyIncoming(m){if(document.visibilityState==="visible"&&selectedUser?.id===m.sender_id)return;if("Notification"in window&&Notification.permission==="granted")new Notification("CHATS",{body:m.message_type==="voice"?"🎙 Voice message":m.message_type==="file"?`📎 ${m.file_name||"File"}`:m.content})}
async function registerSW(){if("serviceWorker"in navigator)try{await navigator.serviceWorker.register("sw.js")}catch(e){}}
$("saveProfile").onclick=async()=>{const name=$("settingsName").value.trim();if(!name)return toast("Enter a name.");const {data,error}=await sb.from("profiles").update({display_name:name}).eq("id",currentUser.id).select().single();if(error)return toast(error.message);profile=data;renderMyProfile();await loadUsers();if(selectedUser?.id===currentUser.id)$("chatName").textContent=name;toast("Profile updated")};
$("avatarInput").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024)return toast("Image is too large. Maximum 5 MB.");toast("Uploading picture…");const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=`avatars/${currentUser.id}-${Date.now()}.${ext}`;const {error:up}=await sb.storage.from("chat-files").upload(path,file,{contentType:file.type||"image/jpeg",upsert:false});if(up)return toast("Picture upload failed: "+up.message);const {data}=sb.storage.from("chat-files").getPublicUrl(path);const {data:updated,error}=await sb.from("profiles").update({avatar_url:data.publicUrl}).eq("id",currentUser.id).select().single();if(error)return toast(error.message);profile=updated;renderMyProfile();await loadUsers();toast("Profile picture updated");e.target.value=""};
$("changePassword").onclick=async()=>{const password=$("newPassword").value;if(password.length<6)return toast("Password must be at least 6 characters.");const {error}=await sb.auth.updateUser({password});if(error)return toast(error.message);$("newPassword").value="";toast("Password changed successfully")};
window.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden")setLastSeen()});window.addEventListener("pagehide",()=>setLastSeen());
sb.auth.getSession().then(async({data})=>{if(data.session)await startApp(data.session.user)});sb.auth.onAuthStateChange(async(event,session)=>{if(event==="SIGNED_OUT")location.reload()});
