-- CHATS SIMPLE
-- Run once in Supabase SQL Editor.
-- Also enable Authentication > Providers > Anonymous sign-ins.

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 display_name text not null default 'New User',
 created_at timestamptz not null default now(),
 is_online boolean not null default false,
 last_seen timestamptz
);

create table if not exists public.messages (
 id bigint generated by default as identity primary key,
 sender_id uuid not null references public.profiles(id) on delete cascade,
 receiver_id uuid not null references public.profiles(id) on delete cascade,
 content text not null check (char_length(content) between 1 and 2000),
 created_at timestamptz not null default now(),
 read_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using (true);

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert to authenticated with check (auth.uid()=id);

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);

drop policy if exists messages_read on public.messages;
create policy messages_read on public.messages for select to authenticated using (auth.uid()=sender_id or auth.uid()=receiver_id);

drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated with check (auth.uid()=sender_id);

drop policy if exists messages_update_read on public.messages;
create policy messages_update_read on public.messages for update to authenticated using (auth.uid()=receiver_id or auth.uid()=sender_id) with check (auth.uid()=receiver_id or auth.uid()=sender_id);

alter table public.messages replica identity full;
do $$ begin
 if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and tablename='messages') then
   alter publication supabase_realtime add table public.messages;
 end if;
end $$;
