/* =========================================================
   CHATS — COMPLETE SUPABASE DATABASE SETUP
   ========================================================= */


/* =========================================================
   1. PROFILES TABLE
   ========================================================= */

create table if not exists public.profiles (
  id uuid primary key
    references auth.users(id)
    on delete cascade,

  display_name text not null default 'User',

  avatar_url text,

  created_at timestamptz not null default now(),

  last_seen timestamptz,

  is_online boolean not null default false,

  last_logout_at timestamptz
);


/* =========================================================
   2. ADD MISSING PROFILE COLUMNS
   ========================================================= */

alter table public.profiles
  add column if not exists display_name text;

alter table public.profiles
  add column if not exists avatar_url text;

alter table public.profiles
  add column if not exists created_at timestamptz
  default now();

alter table public.profiles
  add column if not exists last_seen timestamptz;

alter table public.profiles
  add column if not exists is_online boolean
  default false;

alter table public.profiles
  add column if not exists last_logout_at timestamptz;


/* =========================================================
   3. FIX POSSIBLE NULL VALUES
   ========================================================= */

update public.profiles
set display_name = 'User'
where display_name is null;

update public.profiles
set is_online = false
where is_online is null;


/* =========================================================
   4. PROFILES DEFAULTS
   ========================================================= */

alter table public.profiles
  alter column display_name
  set default 'User';

alter table public.profiles
  alter column is_online
  set default false;


/* =========================================================
   5. MESSAGES TABLE
   ========================================================= */

create table if not exists public.messages (

  id bigint
    generated by default as identity
    primary key,

  sender_id uuid not null
    references public.profiles(id)
    on delete cascade,

  receiver_id uuid not null
    references public.profiles(id)
    on delete cascade,

  content text not null default '',

  message_type text not null default 'text',

  file_url text,

  file_name text,

  file_size bigint,

  created_at timestamptz not null default now(),

  read_at timestamptz
);


/* =========================================================
   6. ADD MISSING MESSAGE COLUMNS
   ========================================================= */

alter table public.messages
  add column if not exists content text
  default '';

alter table public.messages
  add column if not exists message_type text
  default 'text';

alter table public.messages
  add column if not exists file_url text;

alter table public.messages
  add column if not exists file_name text;

alter table public.messages
  add column if not exists file_size bigint;

alter table public.messages
  add column if not exists created_at timestamptz
  default now();

alter table public.messages
  add column if not exists read_at timestamptz;


/* =========================================================
   7. FIX OLD NULL VALUES
   ========================================================= */

update public.messages
set content = ''
where content is null;

update public.messages
set message_type = 'text'
where message_type is null;


/* =========================================================
   8. DEFAULTS
   ========================================================= */

alter table public.messages
  alter column content
  set default '';

alter table public.messages
  alter column message_type
  set default 'text';


/* =========================================================
   9. INDEXES
   ========================================================= */

create index if not exists
messages_sender_receiver_created_idx
on public.messages (
  sender_id,
  receiver_id,
  created_at
);


create index if not exists
messages_receiver_sender_created_idx
on public.messages (
  receiver_id,
  sender_id,
  created_at
);


create index if not exists
messages_receiver_read_idx
on public.messages (
  receiver_id,
  read_at
);


create index if not exists
messages_created_at_idx
on public.messages (
  created_at
);


create index if not exists
profiles_last_seen_idx
on public.profiles (
  last_seen
);


/* =========================================================
   10. ENABLE ROW LEVEL SECURITY
   ========================================================= */

alter table public.profiles
enable row level security;

alter table public.messages
enable row level security;


/* =========================================================
   11. REMOVE OLD PROFILE POLICIES
   ========================================================= */

drop policy if exists
"profiles_select_authenticated"
on public.profiles;

drop policy if exists
"profiles_insert_own"
on public.profiles;

drop policy if exists
"profiles_update_own"
on public.profiles;


/* =========================================================
   12. PROFILE SELECT POLICY
   ========================================================= */

create policy
"profiles_select_authenticated"

on public.profiles

for select

to authenticated

using (
  true
);


/* =========================================================
   13. PROFILE INSERT POLICY
   ========================================================= */

create policy
"profiles_insert_own"

on public.profiles

for insert

to authenticated

with check (
  auth.uid() = id
);


/* =========================================================
   14. PROFILE UPDATE POLICY
   ========================================================= */

create policy
"profiles_update_own"

on public.profiles

for update

to authenticated

using (
  auth.uid() = id
)

with check (
  auth.uid() = id
);


/* =========================================================
   15. REMOVE OLD MESSAGE POLICIES
   ========================================================= */

drop policy if exists
"messages_select_participants"
on public.messages;

drop policy if exists
"messages_insert_sender"
on public.messages;

drop policy if exists
"messages_update_recipient"
on public.messages;

drop policy if exists
"messages_delete_participants"
on public.messages;


/* =========================================================
   16. MESSAGE SELECT POLICY
   ========================================================= */

create policy
"messages_select_participants"

on public.messages

for select

to authenticated

using (
  auth.uid() = sender_id
  or
  auth.uid() = receiver_id
);


/* =========================================================
   17. MESSAGE INSERT POLICY
   ========================================================= */

create policy
"messages_insert_sender"

on public.messages

for insert

to authenticated

with check (
  auth.uid() = sender_id
);


/* =========================================================
   18. MESSAGE UPDATE POLICY
   =========================================================
   
   Mainly used for read_at.
   Only the receiver can update
   received messages.
   ========================================================= */

create policy
"messages_update_recipient"

on public.messages

for update

to authenticated

using (
  auth.uid() = receiver_id
)

with check (
  auth.uid() = receiver_id
);


/* =========================================================
   19. MESSAGE DELETE POLICY
   =========================================================
   
   Allows either participant to clear
   messages from their conversation.
   ========================================================= */

create policy
"messages_delete_participants"

on public.messages

for delete

to authenticated

using (
  auth.uid() = sender_id
  or
  auth.uid() = receiver_id
);


/* =========================================================
   20. REALTIME — MESSAGES
   ========================================================= */

alter table public.messages
replica identity full;


/* =========================================================
   21. REALTIME — PROFILES
   ========================================================= */

alter table public.profiles
replica identity full;


/* =========================================================
   22. ADD MESSAGES TO SUPABASE REALTIME
   ========================================================= */

do $$
begin

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then

    alter publication supabase_realtime
    add table public.messages;

  end if;

end
$$;


/* =========================================================
   23. ADD PROFILES TO SUPABASE REALTIME
   ========================================================= */

do $$
begin

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'profiles'
  ) then

    alter publication supabase_realtime
    add table public.profiles;

  end if;

end
$$;


/* =========================================================
   24. STORAGE BUCKET
   =========================================================
   
   Used for:
   - Profile pictures
   - Photos
   - Videos
   ========================================================= */

insert into storage.buckets (
  id,
  name,
  public
)

values (
  'chat-files',
  'chat-files',
  true
)

on conflict (id)

do update set
  public = true;


/* =========================================================
   25. REMOVE OLD STORAGE POLICIES
   ========================================================= */

drop policy if exists
"chat_files_select"
on storage.objects;

drop policy if exists
"chat_files_insert"
on storage.objects;

drop policy if exists
"chat_files_update"
on storage.objects;

drop policy if exists
"chat_files_delete"
on storage.objects;


/* =========================================================
   26. STORAGE SELECT
   ========================================================= */

create policy
"chat_files_select"

on storage.objects

for select

to public

using (
  bucket_id = 'chat-files'
);


/* =========================================================
   27. STORAGE INSERT
   ========================================================= */

create policy
"chat_files_insert"

on storage.objects

for insert

to authenticated

with check (
  bucket_id = 'chat-files'
);


/* =========================================================
   28. STORAGE UPDATE
   ========================================================= */

create policy
"chat_files_update"

on storage.objects

for update

to authenticated

using (
  bucket_id = 'chat-files'
)

with check (
  bucket_id = 'chat-files'
);


/* =========================================================
   29. STORAGE DELETE
   ========================================================= */

create policy
"chat_files_delete"

on storage.objects

for delete

to authenticated

using (
  bucket_id = 'chat-files'
);


/* =========================================================
   30. FINISHED
   ========================================================= */

select
  'CHATS database setup completed successfully.'
  as status;
